INSERT INTO d_postac VALUES ('Wiedzma Jagma', 'tlo7.jpg-1250x1400', 'widzmaJagma.png');
INSERT INTO d_postac VALUES ('Burmistrz', 'tlo12.jpg-1800x1080', 'burmistrz.png');
INSERT INTO d_postac VALUES ('Mala Asia', 'domekAsiWnetrze.jpg-360x277', 'malaAsia.png');
INSERT INTO d_postac VALUES ('Wedrowiec', 'pubWnetrze.jpg-200x260', 'wedrowiec.png');
INSERT INTO d_postac VALUES ('Kolekcjoner', 'domKolekcjoneraWnetrze.jpg-488x180', 'kolekcjoner.png');
INSERT INTO d_postac VALUES ('Lesnik', 'tlo7.jpg-870x200', 'lesnik.png');
INSERT INTO d_postac VALUES ('Astrolog', 'wiezaAstronomicznaWnetrze.jpg-380x280', 'astrolog.png');
INSERT INTO d_postac VALUES ('Bibliotekarz', 'bibliotekaWnetrze.jpg-100x255', 'bibliotekarz.png');
INSERT INTO d_postac VALUES ('Pokerzysta', 'pubWnetrze.jpg-400x320', 'pokerzytsa.png');
INSERT INTO d_postac VALUES ('Zielarka', 'chataZielarkiWnetrze.jpg-435x237', 'zielarka.png');
INSERT INTO d_postac VALUES ('Loki', 'tlo18.jpg-2380x500', 'loki.png');
INSERT INTO d_postac VALUES ('Andvari', 'jaskiniaWnetrze.jpg-308x260', 'andvari.png');
INSERT INTO d_postac VALUES ('Sindri', 'kopalniaWnetrze.jpg-415x365', 'sindri.png');
INSERT INTO d_postac VALUES ('Brokk', 'kopalniaWnetrze.jpg-115x160', 'brokk.png');
INSERT INTO d_postac VALUES ('Wetkarz', 'tlo11.jpg-100x930', 'wedkarz.png');
INSERT INTO d_postac VALUES ('Medrzec', 'tlo6.jpg-1355x600', 'medrzec.png');
INSERT INTO d_postac VALUES ('Chomik', 'tlo19.jpg-1385x150', 'chomik.png');
INSERT INTO d_postac VALUES ('Malgosia', 'domekMalgosiWnetrze.jpg-370x260', 'malgosia.png');
INSERT INTO d_postac VALUES ('Thor', 'asgardWnetrze.jpg-330x225', 'thor.png');
INSERT INTO d_postac VALUES ('Szwaczka', 'krawiecWnetrze.jpg-540x170', 'szwaczka.png');
INSERT INTO d_postac VALUES ('Mag', 'wiezaCzarodziejaWnetrze.jpg-350x260', 'mag.png');
INSERT INTO d_postac VALUES ('Thrym', 'tlo19.jpg-1700x666', 'thrym.png');
INSERT INTO d_postac VALUES ('Wampir', 'kryptaWampiraWnetrze.jpg-200x200', 'wampir.png');

INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Wiedzma Jagma: Witaj wedrowcze! Podejdz blizej musze Ci sie dobrze przyjrzec! Dobrze. Mam dla Ciebie zadanie!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Ty: Na czym ono ma polegac?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Wiedzma Jagma: Potrzebuje 10 jagod do sporzadzenia eliksiru. Czy mozesz mi je dostarczyc?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Ty: Dobrze. Niebawem wroce/Nic z tego! Zbieraj jagody sama');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Wiedzma Jagma: I jak? Masz dla mnie jagody?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Ty: Tak. Prosze oto one./ Nie. Potrzebuje wiecej czasu');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jagody', 'Wiedzma Jagma', 'Wiedzma Jagma: Dziekuje. Oto Twoja zasluzona nagroda. Zegnaj!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Burmistrz: Ej Ty! Podobno jestes tu nowy?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Ty: Tak. Niedawno trafilem do tej krainy. Czy jest cos co moge dla Pana zrobic?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Burmistrz: Tak. W naszym lesie grasuje watacha wilkow. Atakuja mieszkancow, poluja na nasze bydlo i odstraszaja podroznych. Musimy sie ich pozbyc! Pomozesz mi? Zabij 10 tych bestii, a sowicie Cie wynagrodze');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Ty: Dobrze. Juz sie zabieram za prace/ Nic z tego! Zabijaj wilki sam');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Burmistrz: I jak? Udalo Ci sie zabic te besie?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Ty: Tak/ Jeszcze nie');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wilki w Lesie', 'Burmistrz', 'Burmistrz: Swietnie. Oto Twoja nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', '(Slyszysz placz)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Ty: Ej mala! Co sie stalo?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Mala Asia: Uuu... Na strychu strasza duchy! Strasznie sie boje!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Ty: Spokojnie. Pojde sprawdzic co sie dzieje na tym strychu/ Glupia. Duchow nie ma');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Mala Asia: Uuuu....');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Ty: Spokojnie. Duchow juz nie ma na Twoim strychu/(...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Mala Asia: Naprawde? Pozbyles sie ich? Oj dziekuje, dziekuje, dziekuje! Mam cos dla Ciebie!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Duchy', 'Mala Asia', 'Ty: Dzieki');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Moge sie przysiac?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Wedrowiec: Jasne siadaj!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Co slychac w szerokim swiecie?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Wedrowiec: Wlasnie wrocilem z wyprawy po Gorach Mglistych. Chciaalem zdobyc Sniezny Szczyt i zwiedzic wszystkie jaskinie. Udalo mi sie osiagnac cel ale pogoda byla wyjatkowo trudna. Loki szaleje w tym roku. Ale je jestem zmeczony. Sluchaj. Nie moglbys mi przyniesc eiksiru witalnosci od Jagmy?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Jasne. Juz po niego ide/ Nie. Idz po niego sam');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Czesc Jagmo. Czy mogłabyś coś dla mnie zrobić?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Wiedzma Jagma: A co takiego?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Ty: Eliksir Witalnosci');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Wiedzma Jagma: Aaaa... dobrze. Jesli przyniesiesz mi 10 jagod i zaplacisz mi 100 Zlotych Monet. ');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Ty: Dobrze/ Nie ma mowy');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Ty: Jagmo. Masz wysztkie potrzebne skladniki/(...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Wiedzma Jagma: Swietnie. Oto Twoj eliksir');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wiedzma Jagma', 'Ty: Dziekuje');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Witaj wedrowcze! Mam dla Ciebie eliksir');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Wedrowiec: Ooo.. dziekuje przyjacielu. Mam cos dla Ciebie');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zmeczony gosc', 'Wedrowiec', 'Ty: Dzieki. Do zobaczenia');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wspaniala kolekcja', 'Kolekcjoner', 'Kolekcjoner: Witaj nowy! Podobno zwiedziles juz kawal siata... Czy w trakcie swoich podrozy nie natchnoles sie na jakas ciekawa lalke? Widzisz jestem najwiekszym kolekcjonerem lalek w tej krainie i z chcecia jakas od Ciebie odkupie');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wspaniala kolekcja', 'Kolekcjoner', 'Ty: Tak sie skalada ze mam jedna lalke i z chcecia ja sprzedam/ Niestety nie mam Ci co sprzedac.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wspaniala kolekcja', 'Kolekcjoner', 'Kolekcjoner: O dzieki wielkie! Oto Twoja zaplata');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Lesnik: (Mruczy) cholerni wandale');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Ty: Co u Ciebie slychac?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Lesnik: Do tej pory wszystko bylo w porzadku. Zwierzeta zyly sobie w symbiozie, sadzonki drzew rosly sobie. Istna sielanka! Dopoki nie pojawili się ci wandale! Niszcza las! Podpalaja drzewa i strasznie smieca. Dodatkowo odstraszaja nam turystow. Chcialbm sie ich pozbyc! Wiesz, ze to uceikinierzy z wiezienia?!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Ty: Pomoge Ci znimi/ Nic z tym nie moge zrobic');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Ty: Wandale nie beda juz przeszkadzac/(..)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wandale w lesie', 'Lesnik', 'Lesnik: Swietnie. Oto Twoja nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: O tak. Widze, że Wenus wchodzi w kwartet z Neptunem w konstelacji Koziorozca. Hmmm... ciekawe. Ciekawe!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Ty: Co robisz?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: Badam zachowanie gwiazd na niebie. Moge przepowiedziec Ci przyszlosc');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Ty: Jasne. Mozesz sprobowac/Nie dzieki. Nie wierze w takie bzdury.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: Widze wiele podrozy pod Twoim znakiem. I same sukcesy na Twojej drodze. Tak! Wielkie sukcesy!/ Jak chcesz');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Ty: Nie masz dla mnie jakiejs pracy?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: Wlasciwie to mam. Niebo pokrywa mrok. Potrzebuje lepszej lunety.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Ty: Moge Ci jakas przyniesc/Nie mam na to czasu');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: I jak? Masz ja?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Ty: Tak. Oto ona. Prosze/ Jeszcze nie. Potrzebuje czasu. ');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Spojrz w Gwiazdy', 'Astrolog', 'Astrolog: Swietnie. Oto Twoja nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Biblioteka', 'Bibliotekarz', 'Bibliotekarz: Witaj! Co chcialbys zrobic?Moge wypozyczyc Ci ksiazki ale tez skupuje co ciekawsze okazy');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Biblioteka', 'Bibliotekarz', 'Ty: Witaj! Chce wypozyczyc ksiazke/ Witaj! Chce sprzedac ksiazke/ Witaj! Tak sie tylko rozgladam');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Gra', 'Pokerzysta', 'Pokerzysta: Chcesz ze mna zagrac?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Gra', 'Pokerzysta', 'Ty: Tak/ Innym razem');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Ziola', 'Zielarka', 'Ty: Witaj! Wygladasz na zmartwiona. Moge Ci jakos pomoc?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Ziola', 'Zielarka', 'Zielarka: Wlascicieto tak. Po mojej ojczyznie szalejej ogromna plaga straszliwej choroby. Chorzy sa zmuszani przez zarazka do podrozy do sasiadujacych krain i tak choroba rozprzestrzenia sie jeszcze szybciej. Ale da sie ja powstrzymac. Musisz mi naziebrac tylko 10 sztuk rumianku, 5 lawendy oraz 15 szalwi. Mozesz to zrobic?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Ziola', 'Zielarka', 'Ty: Jasne. Lece sie tym zajac/ Nie. Ne bchodzi mnie to');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Ziola', 'Zielarka', 'Ty: Prosze. To ziola dla Ciebie/(...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Ziola', 'Zielarka', 'Zielarka: O dziekuje. Caly swiat bedzie Ci wdziedzny! Oto Twoja zasluzona nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Burmistrz', 'Burmistrz: O szukalem Cie po calej krainie! Mam dla Ciebie pilne zlecenie. W gorach mglistych grasuje wampir. Za dnia siedzi w krypcie, a w nocy asa naszych obywateli. Zajmij sie nim, a czeka Cie wspaniala nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Burmistrz', 'Ty: Jasne. Juz tam ide/ Moze innym razem');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Burmistrz', 'Burmistrz: Bedziesz potrzebowac osikowego kolka. Idz z tym zleceniem do lesnika');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Ty: Hej! Potrzebuje osikowego kolka');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Lesnik: Dobrze w takim razie przynies mi drewno i zelazo');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Ty: Mam wszystko co chciales/ Jeszcze nic');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Lesnik: Dobrze. Zaplac mi 10 sztuk Zlotych Monet');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Ty: Dobrze/ To za drogo!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Lesnik', 'Lesnik: Oto Twoj kolek');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Wampir', 'Ty: Gin wampirze!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Wampir', 'Wampir: Pozalujesz, ze trafiles do mojej krypty!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Burmistrz', 'Ty: Wampir nie bedzie juz przeszkadzal/ Potrzebuje wiecej czasu');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Wampir', 'Burmistrz', 'Burmistrz: Swietnie. Oto Twoja nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Loki: Witaj podrozny! Nie przeszkadza Ci panujaca tu atmosfera?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Ty: Witaj! Jakos nie bardzo.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Loki: W takim razie mam dla Ciebie zadanie. Musze zdobyc dla Odyna pierscien, ktora zamienia kazdy przedmiot w zloto. Znajdziesz o u krasnoluda Andvariego. Kazdy ruch jest dozwolony. Tylko pamietaj! Nie mozesz zatrzymac pierscienia! On zniszczy kazdego smiertelnika. To jak? Podejmiesz sie?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Ty: Jasne. Ide szukac Andvariego/ Nie ma mowy!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Andvari', 'Ty: Witaj Andvari! Przyszedlem po Twoj pierscien');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Andvari', 'Andvari: To Loki Cie tutaj przyslal? Tak myslalem. Sluchaj. Pojde Ci na reke. Zaplac mi tylko 1000 Zlotych Monet, a pierscien bedzie Twoj');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Andvari', 'Ty: Dobrze. Prosze/ Dobrze. Przyjde za chwile z cala kwota/ Nie ma mowy (walka)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Ty: Loki. Oto Twoj pierscien./(...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Bog Klamstwa', 'Loki', 'Loki: Dzieki. Czeka Cie nagroda!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Sindri', 'Sindri: Pomocy! Pomocy! Pomocy!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Sindri', 'Ty: Co sie stalo?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Sindri', 'Sindri: Wielkie pajaki uprowadzily mojego brata Brokka. Pomoz mu odzyskac wolnosc.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Sindri', 'Ty: Jasne. Juz sie tym zajme/ Nie bede narazac dla niego skory');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Brokk', 'Brokk: Dzieki za uratowanie mi skory. Zaprowadz mnie do mojego brata. Sindriego/ (...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Pajaki', 'Sindri', 'Sindri: Dzieki. Juz myslalem, ze nigdy ie zobacze mojego brata. Oto nagroda/(...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: Witaj wedrowcze!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Ty: Witaj staruszku! Czy moglbys opowiedziec mi o tej krainie?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: Ta kraina nazywa sie Reisenden. Jest przyjazna dla podroznych. Miejscowa udnosc juz przygotowala dla Cebie miejsce. Dom kolo ktorego stoimi od teraz nalezy do Ciebie!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Ty: Ojej. Nie spodzewalem sie takiej gosciny!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: Do Twojej posesji nalezy rowniez studnia nieopodal.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Ty: Moge znalezc tu prace?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: O tak. Mozesz scnac drzewo, robic deski, wydobywac gline, wypalac cegly, wydobywac zelazo, przetapiac je do sztabek, zbieraz zboze i wypiekac chelb. Nie jest to jednak zbyt oplacalne. Malo za to dostaniesz na targu. Wieksze pieniadze mozesz dostac od mieszkancow za wykonywanie za nich prostych zadan. Popytaj ich.');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Ty: Opowiedz mi cos o geografi tego miejsca');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: Na polnoc od Twojej posesji zajduje sie las Patryja, na polnocny wschod sa za to gory nieskonczonosci. na poludniu ciagnie sie pasmo gor mglistych. Po srodku jest kotlina w ktorej miezkancy zbudowali ryneczek. Po krainie grasuja niezezpieczne bestie. Mozna tez zbierac rosliy');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Ty: Dzieki wielkie. To wszystko na ten monent');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Samouczek', 'Medrzec', 'Medrzec: Powodzenia. Jesli bedziesz miec trudnosci w grze zajrzyj do biblioteki. Tam znajdziesz odpowiedz na kazde pytanie');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jedzonko dla chomika', 'Chomik', 'Ty: Jaki slodki chomik. Wyglada na bardzo glodnego');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Jedzonko dla chomika', 'Chomik', 'Ty: Dam mu cos do jedzenia/ Ide. Nic tu po mnie');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Ty: Twoja wieza wyglada niesamowicie magu');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Mag: O dziekuje');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Ty: Cos Cie trapi?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Mag: Widisz. Ktos ukradl mi Palantir. A to bardzo niebezpieczny przedmiot w nieodpowiednich rekach. Dzieki niemu mozna komunikowac sie z innymi magami i siac zamet w ich glowach. Musze go znalezc');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Ty: Podejrzewasz kogos?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Mag: Tak. Lokiego!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Ty: Zajme sie tym/ Radz sobie sam');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Loki', 'Ty: Loki! Wiesz cos o Palantirze?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Loki', 'Loki: Jak dla mnie to bezuzyteczny smiec. Oddam Ci go jesli odpowiedz na moja zagadke: Coś, przed czym w świecie nic nie uciecze, Co gnie żelazo, przegryza miecze, Pożera ptaki, zwierzęta, ziele, Najtwardszy kamień na mąkę miele, Królów nie szczędzi, rozwala mury, Poniża nawet najwyższe góry. ');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Loki', 'Ty: Smierc/Czas/Przemijanie/ Jeszcze pomysle');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Loki', 'Loki: Dobrze. Oto Twoja nagroda/ Zle!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Mag: I jak? Masz go?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Ty: Tak! Oto on./ Nie zaraz wracam');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Palantir', 'Mag', 'Mag: Swietnie. Oto Twoja nagroda');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Malgosia: Witaj w moich skromnych prograch!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Ty: Kim jestes?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Malgosia: Nazywam sie Malgosia i dzis wybieram sie na bal');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Ty: Bal? Moge isc?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Malgosia: Niestety to impreza zamknieta. Gospodarz nie bylby zadowolony gdybym Cie przyprowadzial. Ale mozesz dla mnie cos zrobic? Potrzebuje kremu od Jagmy');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Ty: Dobrze. Przyniose go dla Ciebie/ Nie. Idz sama');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Wiedzma Jagma', 'Ty: Witaj Jagmo! Potrzebuje kremu dla Malgosi');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Wiedzma Jagma', 'Wiedzma Jagma: Wtakim razie musisz mi przyniesc 10 Czerwonych Muchomorow oraz 10 niebieskich grzybow');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Wiedzma Jagma', 'Ty: Mam wszystkie skladniki/ (...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Wiedzma Jagma', 'Wiedzma Jagma: Swietnie! Potrzebuje jeszcze 10 punktow Twojego snu i gotowe');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Wiedzma Jagma', 'Ty: Prosze Malgosu. Oto Twoj krem/ (...)');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Przyjecie u Diabla', 'Malgosia', 'Malgosia: O dziekuje! OtoTwoja nagroda. ( Malgosia rozbiera siei smaruje kremem po czym wsiada na swoja miotle i odlatuje na przyjecie do diabla');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Gdzie on jest? No gdzie?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Ty: Co sie stalo?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Zaginol moj mlot Mjonir. Chodza sluchy po miesie, ze ukradl go Thrym - wielki lofowy olbrzym. Podobno zarzadal w zamian piekna Freye! Co ja mam zrobic?! Loki posunal mipomysl, zebym przebral sie za Freye, poszedl na swoj slub i tam zabil Thryma oraz odzyskal mlot. Myslisz, ze ma to jakis sens?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Ty: Mysle, ze tak. Loki podawal jakies szczegoly?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Tak. Zebym zdobyl suknie slubna i bukiet kwiatow. A on rzuci czar na mnie i sam zamieni sie w moja druzke (Loki potrafi zmieniac plec) i razem odzyskamy mlot. Czy mozesz przyniesc mi te rzeczy?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Ty: Jasne. z checia pomoge/ Radz sobie sam!');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Szwaczka', 'Ty: Dzien dobry! Potrzebuje sukni slubnej. Takiej w rozmiarze XXXL....');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Szwaczka','Szwaczka: Hmmm... Ta bedzie odpowiednia. sprzedam Ci ja za jedyne 100 Zlotych Monet');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Szwaczka', 'Ty: Juz place/ Nie mam tyle pieniedzy. Przyjde pozniej');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Ty: Prosze Thorze. Oto Twoja suknia i kwiaty. /Potrzebuje wiecej czasu');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Swietnie teleportuje siebie Ciebie i Lokiego do Thryma');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thrym', 'Thrym: Jaka piekna jest moja przyszla maluzonka. Czemu masz takie czerwone oczy?');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Loki', 'Loki: Bo cala noc myslala tylko o tobie i nie mogla zmrozyc oka - tak bardzo nie mogla sie doczekac');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thrym', 'Thrym: No juz kochanie. Juz jestem');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Do ataku');
INSERT INTO d_dialog_postaci (nazwa_questa, postac, tekst) VALUES ('Zaginiony Mjonir', 'Thor', 'Thor: Dzieki za pomoc. Nigdy Ci tego nie zapomne. Oto Twoja nagroda');